version: '3.5'

services:
  db_order:
    container_name: db_order
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=wbtech
      - POSTGRES_USER=trainee
    image: postgres:15-alpine
  nats:
    image: nats:latest
    environment:
      - NATS_CLUSTER_ID=${NATS_CLUSTER_ID}
    command: ["--cluster_name", "WBcluster"]
    ports:
      - "4222:4222"
    restart: unless-stopped
    networks:
      - nats-network
  nats-streaming:
    image: nats-streaming:alpine
    environment:
      - STAN_CLUSTER_ID=${NATS_CLUSTER_ID}
      - STAN_NATS_URL=${NATS_URL}
    command: ["--cluster_id", "WBcluster"]
    ports:
      - "4223:4223"
    depends_on:
      - nats
    restart: unless-stopped
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge