version: '3.5'

services:
  db_order:
    image: postgres:15-alpine
    container_name: db_order
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=wbtech
      - POSTGRES_USER=trainee
      

  nats-streaming:
    image: nats-streaming:alpine
    environment:
      - STAN_CLUSTER_ID=wb_cluster
    command: ["--cluster_id=wb_cluster"]  
    ports:
      - "4222:4222"
    restart: unless-stopped
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge